networks:
  analytics_bracelet_net: {}

services:
  analytics_bracelet:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DB_HOST: analytics_bracelet_db
      DB_USER: tester
      DB_PASS: testing123!
      DB_NAME: testing
    depends_on:
      - analytics_bracelet_db
    networks:
      - analytics_bracelet_net
  
  analytics_bracelet_db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=testing123!
      - POSTGRES_DB=testing
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
