services:
  db_postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=testing123!
      - POSTGRES_DB=testing
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
