services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basic_microservice_db
    ports:
      - "5432:5432"

  web_app:
    container_name: web_app
    build:
      context: main_dir
    depends_on:
      - postgres
    environment:
      DB_NAME: basic_microservice_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - /home/maybe/PycharmProjects/aplicationForTheCompanyAndPartners/main_dir:/main_dir