# Generated by Django 5.0.6 on 2024-06-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('partner_description', models.TextField()),
                ('services_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chip_number', models.CharField()),
                ('in_use', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfid', models.CharField(max_length=50)),
                ('in_use', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state_number', models.CharField(max_length=50)),
                ('is_work', models.BooleanField()),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.chip')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='analytics_of_day_machinery_stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_average_speed', models.FloatField()),
                ('total_fuel_consumption', models.FloatField()),
                ('total_engine_hours', models.FloatField()),
                ('total_work_hours', models.FloatField()),
                ('date', models.DateTimeField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('radius', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Бригадир', max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.bracelet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('role', models.TextField()),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.bracelet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.foreman')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='analytics_of_photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_violations', models.PositiveIntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='analytics_of_day_bracelet_stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_entry_time', models.DateTimeField()),
                ('last_exit_time', models.DateTimeField()),
                ('total_timeout', models.FloatField()),
                ('total_untraceable', models.FloatField()),
                ('date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.employee')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.company')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Task_queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='today_bracelet_stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pulse', models.BooleanField()),
                ('timeout', models.FloatField()),
                ('untraceable', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.employee')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='today_machinery_stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('average_speed', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('engine_hours', models.FloatField()),
                ('work_hours', models.FloatField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='total_analytics_of_brigade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_works', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=50)),
                ('quantity_employee', models.PositiveIntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.foreman')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP_app.object')),
            ],
        ),
    ]
